### PR TITLE
SCYLLA-VERSION-GEN: rm unnecessary Bashism

### PR DESCRIPTION
**Pull request by nodakai**
Make Debian's dash happy

### CODE REVIEW

**Review by nyh — APPROVED** [review]
Looks good.
Pending signature on CLA.

**Review by syuu1228 — APPROVED** [review]
LGTM

**Comment by tchaikov** [comment]
@syuu1228 hi Takuya, i think this change is still relevant. can we get it merged?

**Comment by avikivity** [comment]
We need a signed contributor licence agreement from the author.

**Comment by tchaikov** [comment]
@nodakai hi NODA, would you mind following the instructions at https://github.com/scylladb/scylladb/blob/master/CONTRIBUTING.md#contributing-code-to-scylla and sign the CLA ? or if this process is too complicated or you are not working on this anymore, i will create another PR to address this very issue if you don't mind.

**Comment by nodakai** [comment]
@tchaikov Sounds good. You can interpret this as my "bug report", feel free to push a fix of your own

**Comment by tchaikov** [comment]
@nodakai thank you! i created #34 to address this "bug report".

**Pull request closed without merging**
